// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqFPANXHGPHhEMOifOFHzuhZ3GqmbIZGg',
    appId: '1:872710576252:web:d77d5ac0a1e214cb7a51f9',
    messagingSenderId: '872710576252',
    projectId: 'connect-34548',
    authDomain: 'connect-34548.firebaseapp.com',
    storageBucket: 'connect-34548.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ65XA8MotSxAiWf3NzSFaV-f2Bxxc8Fw',
    appId: '1:872710576252:android:f732747fbd27383e7a51f9',
    messagingSenderId: '872710576252',
    projectId: 'connect-34548',
    storageBucket: 'connect-34548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmi_4ogzU-9ZiliiCE7TJA1d3JGbWecQg',
    appId: '1:872710576252:ios:9e418b2f6fead48f7a51f9',
    messagingSenderId: '872710576252',
    projectId: 'connect-34548',
    storageBucket: 'connect-34548.appspot.com',
    iosBundleId: 'it.maionemiky.flutterFirebaseVideoCallWebrtc',
  );

}