// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuZlpLkliSouFIbfmSu3HF2bZkLvfkqvI',
    appId: '1:445435623395:web:49b3e4effcc563628a52d6',
    messagingSenderId: '445435623395',
    projectId: 'flutterfirertc',
    authDomain: 'flutterfirertc.firebaseapp.com',
    storageBucket: 'flutterfirertc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI_-Fvr9MMH7t2f3ijHg3o-DJlhfh4iAM',
    appId: '1:445435623395:android:c7eef4fa622ca17b8a52d6',
    messagingSenderId: '445435623395',
    projectId: 'flutterfirertc',
    storageBucket: 'flutterfirertc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH6wBuFfcFuUWnKjn9oyGS0RzQh5rWmz0',
    appId: '1:445435623395:ios:8584ef5ab6e0f14a8a52d6',
    messagingSenderId: '445435623395',
    projectId: 'flutterfirertc',
    storageBucket: 'flutterfirertc.appspot.com',
    iosBundleId: 'it.maionemiky.flutterFirebaseVideoCallWebrtc',
  );

}